In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## PHASE 1 - DATA EXPLORATION WITH PANDAS

In [4]:
data=pd.read_csv("C:\\Users\\attil\\Downloads\\github_illusion_raw.csv")

In [5]:
data.head()

,username,account_created,last_commit_date,total_repos,total_commits,commit_streak,avg_commit_hour,stars,forks,star_fork_ratio,...,following,readme_score,language,country,has_bio,has_profile_pic,bot_like_score,suspicion_score,profile_age_days,_profile_type
0,wblackburn1825,08-17-2021,"October 11, 2020",47.0,1861.0,304 days,18.0,237.0,125.0,1.896,...,117.0,9.4,c++,JP,1.0,1.0,NO,NaN,2391.0,0
1,reneecampos410,25 May 2012,"November 02, 2022",3.0,1809.0,219,15.0,467.0,41.0,11.390,...,NaN,4.3,Shell,NaN,0.0,0.0,0,NaN,258.0,2
2,paullutz4507,07-21-2022,02-03-2024,91.0,12345.0,100 days,0.0,263.0,0.0,inf,...,8086.0,2.9,kotlin,Germany,0.0,1.0,True,0.614,1187.0,1
3,maureen114013,11/02/2009,16/12/2023,230.0,1834.0,NaN,1.0,435.0,3.0,145.000,...,4101.0,2.2,JAVASCRIPT,uk,0.0,0.0,True,0.783,1832.0,1
4,dayala3658,23/11/2015,18 Nov 2022,76.0,760.0,145 days,22.0,85.0,34.0,2.500,...,375.0,7.2,ruby,NaN,1.0,1.0,0,NaN,1780.0,0

In [6]:
data.shape

(105000, 21)

In [7]:
data.dtypes

username             object
account_created      object
last_commit_date     object
total_repos         float64
total_commits       float64
commit_streak        object
avg_commit_hour     float64
stars               float64
forks               float64
star_fork_ratio     float64
followers           float64
following           float64
readme_score        float64
language             object
country              object
has_bio             float64
has_profile_pic     float64
bot_like_score       object
suspicion_score     float64
profile_age_days    float64
_profile_type         int64
dtype: object

In [9]:
data.describe()

C:\Users\attil\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,total_repos,total_commits,avg_commit_hour,stars,forks,star_fork_ratio,followers,following,readme_score,has_bio,has_profile_pic,suspicion_score,profile_age_days,_profile_type
count,102871.000000,102911.000000,102938.000000,101759.000000,102338.000000,1.050000e+05,102422.000000,102455.000000,99661.000000,102877.000000,102871.000000,73442.000000,102350.000000,105000.000000
mean,110.972412,3957.132833,13.750578,346.326458,29.158436,inf,723.203208,1862.409565,4.924785,0.607113,0.501220,0.409104,3449.740430,0.679390
std,130.652198,4989.902562,10.328119,538.219975,41.931068,NaN,660.725604,2858.533523,2.708092,0.488394,0.500001,0.288757,8677.003499,0.785012
min,2.000000,10.000000,-3.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-99.000000,0.000000
25%,29.000000,1011.000000,9.000000,57.000000,4.000000,2.750000e+00,26.000000,174.000000,2.700000,0.000000,0.000000,0.167000,1303.000000,0.000000
50%,56.000000,1990.000000,14.000000,151.000000,14.000000,6.667000e+00,607.000000,348.000000,4.900000,1.000000,1.000000,0.325000,2719.000000,0.000000
75%,126.500000,2976.000000,19.000000,384.000000,37.000000,7.156575e+01,1305.000000,2880.000000,7.100000,1.000000,1.000000,0.646000,4133.000000,1.000000
max,500.000000,20000.000000,100.000000,7559.000000,632.000000,inf,2000.000000,10000.000000,10.000000,1.000000,1.000000,1.000000,99999.000000,2.000000

In [19]:
data.isnull().sum()
# → Observation: suspicion_score has 30% nulls, readme_score has 5% nulls.
# → commit_streak is object dtype but should be numeric — needs cleaning.
# → bot_like_score has mixed string/boolean types.

username                0
account_created         0
last_commit_date     2086
total_repos          2070
total_commits        2017
commit_streak        2070
avg_commit_hour      2003
stars                3131
forks                2573
star_fork_ratio         0
followers            2508
following            2467
readme_score         5170
language             8403
country              7674
has_bio              2066
has_profile_pic      2045
bot_like_score       3349
suspicion_score     30566
profile_age_days     2571
_profile_type           0
dtype: int64

In [6]:
data[['account_created','last_commit_date']] # should be dates

       account_created   last_commit_date
0           08-17-2021   October 11, 2020
1          25 May 2012  November 02, 2022
2           07-21-2022         02-03-2024
3           11/02/2009         16/12/2023
4           23/11/2015        18 Nov 2022
...                ...                ...
104995  April 25, 2016         08-31-2023
104996      09/03/2012              never
104997      04-20-2019         01/08/2023
104998      2013-02-14   January 09, 2021
104999  March 11, 2022            unknown

[105000 rows x 2 columns]

In [7]:
data['commit_streak'] # should be numeric

0         304 days
1              219
2         100 days
3              NaN
4         145 days
            ...
104995          83
104996         315
104997         500
104998    143 days
104999         315
Name: commit_streak, Length: 105000, dtype: object

In [27]:
data['avg_commit_hour'].min()
data['avg_commit_hour'].max()

np.float64(-3.0)

In [31]:
data['language'].value_counts() # category

language
typescript    2834
Kotlin        2827
go            2824
PYTHON        2822
r             2804
Java          2800
python        2797
PHP           2797
javascript    2792
Rust          2779
Go            2776
R             2776
Shell         2767
JavaScript    2765
TypeScript    2762
GO            2761
Python        2759
Swift         2754
ruby          2739
JAVASCRIPT    2736
Unknown       2731
java          2730
JAVA          2729
php           2713
kotlin        2710
shell         2703
PHP           2698
C++           2698
c++           2695
rust          2686
SHELL         2674
swift         2671
Ruby          2655
unknown       2640
Name: count, dtype: int64

In [33]:
data['country'].unique() # category

array(['JP', nan, 'Germany', 'uk', 'canada', 'Australia', 'china', 'IND',
       'brazil', 'India', 'FR', 'US', 'AU', 'russia', 'United Kingdom',
       'Japan', 'DE', 'germany', 'China', 'BR', 'United States', 'Brazil',
       'india', 'japan', 'france', 'australia', 'UK', 'IN', 'USA', 'RU',
       'Canada', 'CN', 'Russia', 'CA', 'us', 'Unknown', 'united states',
       'France'], dtype=object)

In [10]:
data['bot_like_score'] # category (0 or 1)

0            NO
1             0
2          True
3          True
4             0
          ...
104995        0
104996       No
104997      Yes
104998        0
104999    False
Name: bot_like_score, Length: 105000, dtype: object

In [11]:
data.duplicated(subset='username').sum()

np.int64(3193)

In [12]:
data['star_fork_ratio'].describe()

C:\Users\attil\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    1.050000e+05
mean              inf
std               NaN
min      0.000000e+00
25%      2.750000e+00
50%      6.667000e+00
75%      7.156575e+01
max               inf
Name: star_fork_ratio, dtype: float64

In [13]:
data['profile_age_days'].describe()

count    102350.000000
mean       3449.740430
std        8677.003499
min         -99.000000
25%        1303.000000
50%        2719.000000
75%        4133.000000
max       99999.000000
Name: profile_age_days, dtype: float64

In [14]:
data['bot_like_score'].value_counts(dropna=False)

bot_like_score
0        26708
1        16198
no       11217
False     7926
NO        7833
No        7785
yes       7716
Yes       4221
YES       4180
True      4165
maybe     3590
NaN       3461
Name: count, dtype: int64

In [15]:
data['suspicion_score'].isnull().mean()

np.float64(0.30055238095238096)